### PR TITLE
Add Nx

### LINKED ISSUE #8: Install and configure Nx workspace
Create a root package.json to support managing the repository as a monrepo:

https://docs.npmjs.com/cli/v8/using-npm/workspaces

> *Note*: Yarn users will need to enable experimental workspace support.
>
> https://classic.yarnpkg.com/lang/en/docs/workspaces/#toc-tips-tricks

Follow the setup steps to add Nx to an existing monorepo: https://nx.dev/getting-started/nx-setup#add-nx-to-an-existing-project

### PR DESCRIPTION
**Pull request by brebory**
See the details in #8, that explains all the steps followed here. There was one additional change - when I was running the application using the new Nx workspace commands `nx server uct-locator-back-end` (see README.md for more details), I was looking at the `passport.js` configuration and noticed that an import path could be simplified, so I did so.

Closes #8

### CODE REVIEW

**Review by josephmaxwellhyland — COMMENTED** [review]
This all looks good to me, works better than the old setup for sure! Did we want to merge this into `develop` first though?

**Comment by brebory** [comment]
> This all looks good to me, works better than the old setup for sure! Did we want to merge this into `develop` first though?

Updated the base branch!

**Review by josephmaxwellhyland — APPROVED** [review]
Good to go!

**Review by hylandtechoutreach — COMMENTED** [review]
👍

**Pull request merged**
